ALTER TABLE masters ADD COLUMN IF NOT EXISTS public_slug TEXT;
ALTER TABLE masters ADD COLUMN IF NOT EXISTS specialization TEXT;
ALTER TABLE masters ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE masters ADD COLUMN IF NOT EXISTS phone TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_masters_public_slug_unique
  ON masters(public_slug)
  WHERE public_slug IS NOT NULL;

ALTER TABLE master_services ADD COLUMN IF NOT EXISTS price_cents INTEGER NOT NULL DEFAULT 0;
ALTER TABLE master_services ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
